create table reader
(
    id         integer generated by default as identity
        primary key,
    name       varchar(100) not null unique ,
    birthday   date         not null,
    membership integer
);

create table book
  (
      id        integer generated by default as identity
          primary key,
      title     varchar not null,
      author    varchar,
      year      varchar,
      owner     integer references reader(id),
      date_take date
  );